server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quartz?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: quartz
    driver-class-name: com.mysql.jdbc.Driver
  liquibase:
    enabled: true
    default-schema: quartz
    change-log: classpath:db/changelog/db.changelog-master.yaml
    #    change-log: file:./src/main/resources/db/changelog/changes/db.changelog-master.yaml
  jpa:
    hibernate:
      primary-dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        order_inserts: true
        order_updates: true
        format_sql: false
        jdbc:
          batch_versioned_data: true
          batch_size: 1000
          lob.non_contextual_creation: true
  quartz:
    autoStartup: true
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_

            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true




logging:
  level:
    ROOT: info
    org.ming: debug
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  file:
    name: log/quartz.log
  ##### these are used by log lib #####
  console:
    enabled: true
  # used for request/response body by DEBUG level, default 16384



